const keys = ['loading','user','noRecords','pin','unpin','rename','delete','currentPlan','freeUser','upgrade','profile','settings','logout','emptyTitle','emptyDesc','ppt','analysis','summary','polish','translate','extract','thinking','preview','copy','jumpLatest','workspace','placeholder','continuePlaceholder','stop','send','support','files','retry','download','deleteTitle','deleteText','cancel','confirmDelete','accountAccess','role','admin','member','appearance','darkMode','darkDesc','notifications','sound','soundDesc'];
const values = {
  'zh-CN':['加载中…','用户','暂无记录','置顶对话','取消置顶','重命名','删除','当前套餐','免费版用户','升级套餐','个人资料','设置','退出登录','我能帮您做什么？','上传 Excel、Word 或 PPT，并描述需求，我会自动完成文档处理。','生成演示文稿','深度数据分析','极速提炼总结','智能公文润色','专业内容翻译','结构化数据提取','思考中…','预览','复制回复','回到最新消息','文件工作区','上传文档并描述您的需求…','在此文件基础上继续补充需求…','停止生成','发送','支持 PDF、Excel、Word、PPT 和常见图片，可连续发送指令。','文件','重试','下载','删除确认','确定删除这条历史记录吗？删除后文档及对话无法恢复。','取消','确认删除','账户权限','当前角色','超级管理员','普通用户','外观偏好','深色模式','切换至暗黑主题界面','通知设置','任务完成提示音','大文件处理完毕时播放声音'],
  en:['Loading…','User','No records','Pin conversation','Unpin conversation','Rename','Delete','Current plan','Free plan','Upgrade plan','Profile','Settings','Log out','What can I help you with?','Upload Excel, Word, or PPT and describe what you need.','Create a presentation','Advanced data analysis','Summarize a document','Polish business writing','Translate content','Extract structured data','Thinking…','Preview','Copy response','Jump to latest','File workspace','Upload a document and describe your request…','Continue working on this file…','Stop generating','Send','Supports PDF, Excel, Word, PPT, and common images. You can send follow-up instructions.','Files','Retry','Download','Delete conversation','Delete this history item? Its documents and conversation cannot be recovered.','Cancel','Delete','Account access','Current role','Administrator','Member','Appearance','Dark mode','Switch to a dark interface','Notifications','Completion sound','Play a sound when large-file processing finishes'],
  ja:['読み込み中…','ユーザー','履歴はありません','会話を固定','固定を解除','名前を変更','削除','現在のプラン','無料プラン','プランをアップグレード','プロフィール','設定','ログアウト','何をお手伝いできますか？','Excel、Word、PPT をアップロードして要望を入力してください。','プレゼンを作成','高度なデータ分析','文書を要約','ビジネス文書を校正','文書を翻訳','構造化データを抽出','思考中…','プレビュー','回答をコピー','最新へ移動','ファイルワークスペース','文書をアップロードして要望を入力…','このファイルへの追加要望…','生成を停止','送信','PDF、Excel、Word、PPT、一般的な画像に対応。続けて指示できます。','ファイル','再試行','ダウンロード','会話を削除','この履歴を削除しますか？文書と会話は復元できません。','キャンセル','削除する','アカウント権限','現在の役割','管理者','一般ユーザー','外観','ダークモード','暗い画面に切り替える','通知','完了通知音','大きなファイルの処理完了時に音を鳴らす'],
  ko:['불러오는 중…','사용자','기록 없음','대화 고정','고정 해제','이름 변경','삭제','현재 요금제','무료 요금제','요금제 업그레이드','프로필','설정','로그아웃','무엇을 도와드릴까요?','Excel, Word 또는 PPT를 업로드하고 원하는 작업을 설명하세요.','프레젠테이션 만들기','고급 데이터 분석','문서 요약','비즈니스 문서 다듬기','콘텐츠 번역','구조화 데이터 추출','생각 중…','미리보기','응답 복사','최신 메시지로','파일 작업 공간','문서를 업로드하고 요청을 설명하세요…','이 파일에 추가 요청…','생성 중지','보내기','PDF, Excel, Word, PPT 및 일반 이미지를 지원하며 후속 지시를 보낼 수 있습니다.','파일','다시 시도','다운로드','대화 삭제','이 기록을 삭제할까요? 문서와 대화는 복구할 수 없습니다.','취소','삭제','계정 권한','현재 역할','관리자','일반 사용자','화면 설정','다크 모드','어두운 화면으로 전환','알림','완료 알림음','대용량 파일 처리 완료 시 소리 재생'],
  es:['Cargando…','Usuario','Sin registros','Fijar conversación','Desfijar conversación','Renombrar','Eliminar','Plan actual','Plan gratuito','Mejorar plan','Perfil','Ajustes','Cerrar sesión','¿En qué puedo ayudarte?','Sube Excel, Word o PPT y describe lo que necesitas.','Crear presentación','Análisis avanzado','Resumir documento','Mejorar redacción','Traducir contenido','Extraer datos estructurados','Pensando…','Vista previa','Copiar respuesta','Ir al final','Espacio de archivos','Sube un documento y describe tu solicitud…','Continúa trabajando en este archivo…','Detener generación','Enviar','Admite PDF, Excel, Word, PPT e imágenes comunes, con instrucciones consecutivas.','Archivos','Reintentar','Descargar','Eliminar conversación','¿Eliminar este historial? Los documentos y la conversación no se podrán recuperar.','Cancelar','Eliminar','Acceso de cuenta','Rol actual','Administrador','Usuario','Apariencia','Modo oscuro','Cambiar a interfaz oscura','Notificaciones','Sonido de finalización','Reproducir sonido al terminar archivos grandes'],
  pt:['Carregando…','Usuário','Sem registros','Fixar conversa','Desafixar conversa','Renomear','Excluir','Plano atual','Plano gratuito','Melhorar plano','Perfil','Configurações','Sair','Como posso ajudar?','Envie Excel, Word ou PPT e descreva o que precisa.','Criar apresentação','Análise avançada','Resumir documento','Aprimorar texto','Traduzir conteúdo','Extrair dados estruturados','Pensando…','Visualizar','Copiar resposta','Ir para o final','Área de arquivos','Envie um documento e descreva o pedido…','Continue trabalhando neste arquivo…','Parar geração','Enviar','Compatível com PDF, Excel, Word, PPT e imagens comuns, com instruções contínuas.','Arquivos','Tentar novamente','Baixar','Excluir conversa','Excluir este histórico? Documentos e conversa não poderão ser recuperados.','Cancelar','Excluir','Acesso da conta','Função atual','Administrador','Usuário','Aparência','Modo escuro','Mudar para interface escura','Notificações','Som de conclusão','Tocar som ao concluir arquivos grandes'],
  fr:['Chargement…','Utilisateur','Aucun historique','Épingler','Désépingler','Renommer','Supprimer','Forfait actuel','Forfait gratuit','Améliorer le forfait','Profil','Paramètres','Déconnexion','Comment puis-je vous aider ?','Importez Excel, Word ou PPT et décrivez votre besoin.','Créer une présentation','Analyse avancée','Résumer un document','Améliorer la rédaction','Traduire du contenu','Extraire des données structurées','Réflexion…','Aperçu','Copier la réponse','Aller au plus récent','Espace fichiers','Importez un document et décrivez votre demande…','Poursuivez sur ce fichier…','Arrêter la génération','Envoyer','Prend en charge PDF, Excel, Word, PPT et les images courantes avec des instructions successives.','Fichiers','Réessayer','Télécharger','Supprimer la conversation','Supprimer cet historique ? Les documents et la conversation seront irrécupérables.','Annuler','Supprimer','Accès au compte','Rôle actuel','Administrateur','Utilisateur','Apparence','Mode sombre','Passer à une interface sombre','Notifications','Son de fin','Jouer un son à la fin des gros traitements'],
  de:['Laden…','Benutzer','Keine Einträge','Unterhaltung anheften','Anheften lösen','Umbenennen','Löschen','Aktueller Tarif','Kostenloser Tarif','Tarif upgraden','Profil','Einstellungen','Abmelden','Wie kann ich helfen?','Laden Sie Excel, Word oder PPT hoch und beschreiben Sie Ihr Ziel.','Präsentation erstellen','Erweiterte Datenanalyse','Dokument zusammenfassen','Geschäftstext verbessern','Inhalt übersetzen','Strukturierte Daten extrahieren','Denkt nach…','Vorschau','Antwort kopieren','Zur neuesten Nachricht','Dateibereich','Dokument hochladen und Anfrage beschreiben…','An dieser Datei weiterarbeiten…','Generierung stoppen','Senden','Unterstützt PDF, Excel, Word, PPT und gängige Bilder sowie Folgeanweisungen.','Dateien','Erneut versuchen','Herunterladen','Unterhaltung löschen','Diesen Verlauf löschen? Dokumente und Unterhaltung können nicht wiederhergestellt werden.','Abbrechen','Löschen','Kontozugriff','Aktuelle Rolle','Administrator','Benutzer','Darstellung','Dunkler Modus','Zu einer dunklen Oberfläche wechseln','Benachrichtigungen','Abschlusston','Ton nach Verarbeitung großer Dateien abspielen'],
};
export function dashboardCopy(locale) { return Object.fromEntries(keys.map((key, index) => [key, (values[locale] || values['zh-CN'])[index]])); }

const overviewKeys = ['subtitle','conversations','tasks','tokens','timeSaved','hours','lastSevenDays','noActivity','taskHealth','completionRate','completed','processing','failed'];
const overviewValues = {
  'zh-CN': ['查看任务使用情况与近期效率趋势','会话总数','处理任务','累计 Tokens','预估节省时间','小时','近 7 日任务趋势','最近 7 天暂无任务','任务完成情况','完成率','已完成','处理中','失败或取消','最近活动','轮对话'],
  en: ['Review your usage and recent productivity trends','Conversations','Tasks processed','Total tokens','Estimated time saved','hours','Tasks in the last 7 days','No tasks in the last 7 days','Task health','Completion rate','Completed','In progress','Failed or cancelled','Recent activity','turns'],
  ja: ['利用状況と最近の生産性を確認','会話数','処理タスク','合計 Tokens','推定短縮時間','時間','直近 7 日間のタスク','直近 7 日間にタスクはありません','タスク状況','完了率','完了','処理中','失敗またはキャンセル','最近のアクティビティ','ターン'],
  ko: ['사용 현황과 최근 생산성 추세를 확인하세요','대화 수','처리 작업','누적 Tokens','예상 절약 시간','시간','최근 7일 작업 추세','최근 7일간 작업이 없습니다','작업 상태','완료율','완료','처리 중','실패 또는 취소','최근 활동','턴'],
  es: ['Consulta el uso y las tendencias recientes de productividad','Conversaciones','Tareas procesadas','Tokens totales','Tiempo estimado ahorrado','horas','Tareas de los últimos 7 días','No hay tareas en los últimos 7 días','Estado de tareas','Tasa de finalización','Completadas','En curso','Fallidas o canceladas','Actividad reciente','turnos'],
  pt: ['Veja o uso e as tendências recentes de produtividade','Conversas','Tarefas processadas','Tokens totais','Tempo estimado economizado','horas','Tarefas nos últimos 7 dias','Nenhuma tarefa nos últimos 7 dias','Saúde das tarefas','Taxa de conclusão','Concluídas','Em andamento','Falhas ou canceladas','Atividade recente','turnos'],
  fr: ['Consultez votre utilisation et vos tendances récentes','Conversations','Tâches traitées','Tokens cumulés','Temps estimé gagné','heures','Tâches des 7 derniers jours','Aucune tâche ces 7 derniers jours','État des tâches','Taux de réussite','Terminées','En cours','Échouées ou annulées','Activité récente','tours'],
  de: ['Nutzung und aktuelle Produktivitätstrends ansehen','Unterhaltungen','Verarbeitete Aufgaben','Tokens gesamt','Geschätzte Zeitersparnis','Stunden','Aufgaben der letzten 7 Tage','Keine Aufgaben in den letzten 7 Tagen','Aufgabenstatus','Abschlussrate','Abgeschlossen','In Bearbeitung','Fehlgeschlagen oder abgebrochen','Letzte Aktivitäten','Runden'],
};
const overviewExtras = {
  'zh-CN': { creditOverview:'Credits 使用概况',currentBalance:'当前余额',monthUsage:'本月消耗',lastSevenUsage:'近 7 日消耗',estimatedDays:'预计可用',days:'天',noEstimate:'暂无消耗',outputs:'文件产出',monthlyEfficiency:'本月效率',averageDuration:'平均任务耗时',seconds:'秒',thisMonthTasks:'本月任务',monthComparison:'较上月',unchanged:'持平' },
  en: { creditOverview:'Credits usage',currentBalance:'Current balance',monthUsage:'Used this month',lastSevenUsage:'Used in 7 days',estimatedDays:'Estimated runway',days:'days',noEstimate:'No usage yet',outputs:'File output',monthlyEfficiency:'Monthly efficiency',averageDuration:'Average task time',seconds:'sec',thisMonthTasks:'Tasks this month',monthComparison:'vs last month',unchanged:'No change' },
  ja: { creditOverview:'Credits 利用状況',currentBalance:'現在の残高',monthUsage:'今月の消費',lastSevenUsage:'直近 7 日の消費',estimatedDays:'利用可能日数',days:'日',noEstimate:'消費なし',outputs:'ファイル出力',monthlyEfficiency:'今月の効率',averageDuration:'平均処理時間',seconds:'秒',thisMonthTasks:'今月のタスク',monthComparison:'前月比',unchanged:'変化なし' },
  ko: { creditOverview:'Credits 사용 현황',currentBalance:'현재 잔액',monthUsage:'이번 달 사용',lastSevenUsage:'최근 7일 사용',estimatedDays:'예상 사용 가능',days:'일',noEstimate:'사용 내역 없음',outputs:'파일 결과물',monthlyEfficiency:'이번 달 효율',averageDuration:'평균 작업 시간',seconds:'초',thisMonthTasks:'이번 달 작업',monthComparison:'전월 대비',unchanged:'변동 없음' },
  es: { creditOverview:'Uso de Credits',currentBalance:'Saldo actual',monthUsage:'Uso del mes',lastSevenUsage:'Uso en 7 días',estimatedDays:'Duración estimada',days:'días',noEstimate:'Sin consumo',outputs:'Archivos generados',monthlyEfficiency:'Eficiencia mensual',averageDuration:'Tiempo medio',seconds:'s',thisMonthTasks:'Tareas del mes',monthComparison:'frente al mes anterior',unchanged:'Sin cambios' },
  pt: { creditOverview:'Uso de Credits',currentBalance:'Saldo atual',monthUsage:'Uso no mês',lastSevenUsage:'Uso em 7 dias',estimatedDays:'Duração estimada',days:'dias',noEstimate:'Sem consumo',outputs:'Arquivos gerados',monthlyEfficiency:'Eficiência mensal',averageDuration:'Tempo médio',seconds:'s',thisMonthTasks:'Tarefas do mês',monthComparison:'vs. mês anterior',unchanged:'Sem alteração' },
  fr: { creditOverview:'Utilisation des Credits',currentBalance:'Solde actuel',monthUsage:'Utilisés ce mois',lastSevenUsage:'Utilisés sur 7 jours',estimatedDays:'Autonomie estimée',days:'jours',noEstimate:'Aucune consommation',outputs:'Fichiers générés',monthlyEfficiency:'Efficacité mensuelle',averageDuration:'Durée moyenne',seconds:'s',thisMonthTasks:'Tâches du mois',monthComparison:'par rapport au mois dernier',unchanged:'Stable' },
  de: { creditOverview:'Credits-Nutzung',currentBalance:'Aktuelles Guthaben',monthUsage:'Diesen Monat verbraucht',lastSevenUsage:'In 7 Tagen verbraucht',estimatedDays:'Geschätzte Reichweite',days:'Tage',noEstimate:'Noch kein Verbrauch',outputs:'Erstellte Dateien',monthlyEfficiency:'Monatliche Effizienz',averageDuration:'Ø Aufgabenzeit',seconds:'Sek.',thisMonthTasks:'Aufgaben diesen Monat',monthComparison:'zum Vormonat',unchanged:'Unverändert' },
};
export function dashboardOverviewCopy(locale) {
  const selected = overviewValues[locale] || overviewValues['zh-CN'];
  return { ...Object.fromEntries(overviewKeys.map((key, index) => [key, selected[index]])), ...(overviewExtras[locale] || overviewExtras['zh-CN']) };
}

const extra = {
  'zh-CN': { you:'您', processing:'正在处理任务', completed:'已完成', thinkingDone:'思考完成', plan:'任务计划', continuing:'正在继续生成…', second:'秒', minute:'分', deepThinking:'深度思考中', root:'根目录', searchFiles:'搜索工作区文件', uploadFile:'上传文件', refreshFiles:'刷新文件', readingWorkspace:'正在读取工作区…', emptyWorkspace:'工作区暂无文件', workspaceFailed:'工作区读取失败', uploadFailed:'上传失败', renameFailed:'重命名失败', deleteFailed:'删除失败', newFilename:'输入新的文件名', deleteFile:'确定删除“{name}”吗？', fullscreen:'全屏预览', exitFullscreen:'退出全屏预览', closePreview:'关闭预览', previewFailed:'实时预览加载失败', generatingPreview:'正在生成，预览会随 OfficeGPT 文档引擎实时更新…', generatingArtifact:'生成中 · 点击查看实时预览', openPreview:'点击打开预览', fileTimeline:'会话文件时间线', jumpFile:'跳转到文件' },
  en: { you:'You', processing:'Processing task', completed:'Completed', thinkingDone:'Thought complete', plan:'Task plan', continuing:'Continuing generation…', second:'sec', minute:'min', deepThinking:'Thinking deeply', root:'Root', searchFiles:'Search workspace files', uploadFile:'Upload file', refreshFiles:'Refresh files', readingWorkspace:'Reading workspace…', emptyWorkspace:'No files in this workspace', workspaceFailed:'Could not read workspace', uploadFailed:'Upload failed', renameFailed:'Rename failed', deleteFailed:'Delete failed', newFilename:'Enter a new file name', deleteFile:'Delete “{name}”?', fullscreen:'Full-screen preview', exitFullscreen:'Exit full screen', closePreview:'Close preview', previewFailed:'Live preview failed to load', generatingPreview:'Generating. The preview updates in real time…', generatingArtifact:'Generating · Open live preview', openPreview:'Open preview', fileTimeline:'Conversation files', jumpFile:'Jump to file' },
  ja: { you:'あなた', processing:'タスクを処理中', completed:'完了', thinkingDone:'思考完了', plan:'タスク計画', continuing:'生成を続行中…', second:'秒', minute:'分', deepThinking:'深く思考中', root:'ルート', searchFiles:'ワークスペースを検索', uploadFile:'ファイルをアップロード', refreshFiles:'更新', readingWorkspace:'読み込み中…', emptyWorkspace:'ファイルはありません', workspaceFailed:'読み込みに失敗しました', uploadFailed:'アップロード失敗', renameFailed:'名前変更失敗', deleteFailed:'削除失敗', newFilename:'新しいファイル名', deleteFile:'「{name}」を削除しますか？', fullscreen:'全画面プレビュー', exitFullscreen:'全画面を終了', closePreview:'プレビューを閉じる', previewFailed:'プレビューを読み込めません', generatingPreview:'生成中。プレビューはリアルタイムで更新されます…', generatingArtifact:'生成中・ライブプレビューを開く', openPreview:'プレビューを開く', fileTimeline:'会話ファイル', jumpFile:'ファイルへ移動' },
  ko: { you:'나', processing:'작업 처리 중', completed:'완료', thinkingDone:'생각 완료', plan:'작업 계획', continuing:'계속 생성 중…', second:'초', minute:'분', deepThinking:'심층 사고 중', root:'루트', searchFiles:'작업 공간 파일 검색', uploadFile:'파일 업로드', refreshFiles:'새로고침', readingWorkspace:'작업 공간 읽는 중…', emptyWorkspace:'파일이 없습니다', workspaceFailed:'작업 공간 읽기 실패', uploadFailed:'업로드 실패', renameFailed:'이름 변경 실패', deleteFailed:'삭제 실패', newFilename:'새 파일 이름 입력', deleteFile:'“{name}”을 삭제할까요?', fullscreen:'전체 화면 미리보기', exitFullscreen:'전체 화면 종료', closePreview:'미리보기 닫기', previewFailed:'실시간 미리보기 로드 실패', generatingPreview:'생성 중이며 미리보기가 실시간 업데이트됩니다…', generatingArtifact:'생성 중 · 실시간 미리보기 열기', openPreview:'미리보기 열기', fileTimeline:'대화 파일', jumpFile:'파일로 이동' },
  es: { you:'Tú', processing:'Procesando tarea', completed:'Completado', thinkingDone:'Razonamiento completo', plan:'Plan de tarea', continuing:'Continuando la generación…', second:'s', minute:'min', deepThinking:'Razonando', root:'Raíz', searchFiles:'Buscar archivos', uploadFile:'Subir archivo', refreshFiles:'Actualizar', readingWorkspace:'Leyendo espacio…', emptyWorkspace:'No hay archivos', workspaceFailed:'No se pudo leer el espacio', uploadFailed:'Error al subir', renameFailed:'Error al renombrar', deleteFailed:'Error al eliminar', newFilename:'Nuevo nombre de archivo', deleteFile:'¿Eliminar “{name}”?', fullscreen:'Vista previa completa', exitFullscreen:'Salir de pantalla completa', closePreview:'Cerrar vista previa', previewFailed:'No se pudo cargar la vista previa', generatingPreview:'Generando; la vista previa se actualiza en tiempo real…', generatingArtifact:'Generando · Abrir vista en vivo', openPreview:'Abrir vista previa', fileTimeline:'Archivos de conversación', jumpFile:'Ir al archivo' },
  pt: { you:'Você', processing:'Processando tarefa', completed:'Concluído', thinkingDone:'Raciocínio concluído', plan:'Plano da tarefa', continuing:'Continuando a geração…', second:'s', minute:'min', deepThinking:'Pensando profundamente', root:'Raiz', searchFiles:'Pesquisar arquivos', uploadFile:'Enviar arquivo', refreshFiles:'Atualizar', readingWorkspace:'Lendo área…', emptyWorkspace:'Nenhum arquivo', workspaceFailed:'Falha ao ler a área', uploadFailed:'Falha no envio', renameFailed:'Falha ao renomear', deleteFailed:'Falha ao excluir', newFilename:'Novo nome do arquivo', deleteFile:'Excluir “{name}”?', fullscreen:'Visualização em tela cheia', exitFullscreen:'Sair da tela cheia', closePreview:'Fechar visualização', previewFailed:'Falha ao carregar visualização', generatingPreview:'Gerando; a visualização é atualizada em tempo real…', generatingArtifact:'Gerando · Abrir visualização ao vivo', openPreview:'Abrir visualização', fileTimeline:'Arquivos da conversa', jumpFile:'Ir para o arquivo' },
  fr: { you:'Vous', processing:'Traitement en cours', completed:'Terminé', thinkingDone:'Réflexion terminée', plan:'Plan de tâche', continuing:'Génération en cours…', second:'s', minute:'min', deepThinking:'Réflexion approfondie', root:'Racine', searchFiles:'Rechercher des fichiers', uploadFile:'Importer un fichier', refreshFiles:'Actualiser', readingWorkspace:'Lecture de l’espace…', emptyWorkspace:'Aucun fichier', workspaceFailed:'Lecture impossible', uploadFailed:'Échec de l’import', renameFailed:'Échec du renommage', deleteFailed:'Échec de la suppression', newFilename:'Nouveau nom du fichier', deleteFile:'Supprimer « {name} » ?', fullscreen:'Aperçu plein écran', exitFullscreen:'Quitter le plein écran', closePreview:'Fermer l’aperçu', previewFailed:'Impossible de charger l’aperçu', generatingPreview:'Génération en cours ; l’aperçu se met à jour en temps réel…', generatingArtifact:'Génération · Ouvrir l’aperçu en direct', openPreview:'Ouvrir l’aperçu', fileTimeline:'Fichiers de la conversation', jumpFile:'Aller au fichier' },
  de: { you:'Sie', processing:'Aufgabe wird verarbeitet', completed:'Abgeschlossen', thinkingDone:'Überlegung abgeschlossen', plan:'Aufgabenplan', continuing:'Generierung wird fortgesetzt…', second:'Sek.', minute:'Min.', deepThinking:'Denkt gründlich nach', root:'Stammordner', searchFiles:'Dateien durchsuchen', uploadFile:'Datei hochladen', refreshFiles:'Aktualisieren', readingWorkspace:'Dateibereich wird gelesen…', emptyWorkspace:'Keine Dateien vorhanden', workspaceFailed:'Dateibereich konnte nicht gelesen werden', uploadFailed:'Upload fehlgeschlagen', renameFailed:'Umbenennen fehlgeschlagen', deleteFailed:'Löschen fehlgeschlagen', newFilename:'Neuer Dateiname', deleteFile:'„{name}“ löschen?', fullscreen:'Vollbildvorschau', exitFullscreen:'Vollbild beenden', closePreview:'Vorschau schließen', previewFailed:'Vorschau konnte nicht geladen werden', generatingPreview:'Wird erstellt; die Vorschau aktualisiert sich live…', generatingArtifact:'Wird erstellt · Live-Vorschau öffnen', openPreview:'Vorschau öffnen', fileTimeline:'Unterhaltungsdateien', jumpFile:'Zur Datei springen' },
};
export function dashboardExtra(locale) { return extra[locale] || extra['zh-CN']; }

const suggestionValues = {
  'zh-CN': [['帮我写一份年度述职 PPT 的详细大纲，包含数据回顾…','请帮我写一份年度述职 PPT 的详细大纲，包含数据回顾和明年规划。'],['分析 Excel 表格中的月度财务趋势，找出异常数据…','请分析这份 Excel 表格中的月度财务趋势，找出异常数据并生成总结报告。'],['总结超长文档，提取核心观点、关键数据和最终结论…','请总结这份超长文档，提取核心观点、关键数据和最终结论。'],['专业润色公文并纠正语病…','请专业润色这份公文，纠正语病并调整为正式商业风格。'],['保留结构并进行专业的双语翻译…','请对接下来的文档进行双语翻译，保留核心结构，语气专业自然。'],['提取姓名、金额和日期等结构化数据…','请提取文档中的姓名、金额和日期等结构化数据，并用表格展示。']],
  en: [['Draft an annual review PPT with results and future plans…','Create a detailed annual review PPT outline with a data review and plans for next year.'],['Analyze monthly financial trends and identify anomalies…','Analyze monthly financial trends in this Excel file, identify anomalies, and create a summary report.'],['Summarize a long document and extract key conclusions…','Summarize this long document and extract its main ideas, key data, and conclusions.'],['Polish a business document and correct language issues…','Professionally polish this document, correct language issues, and use a formal business tone.'],['Create a natural bilingual translation while preserving structure…','Translate the next document bilingually while preserving its structure and professional tone.'],['Extract names, amounts, dates, and other structured data…','Extract structured data such as names, amounts, and dates, and present it in a table.']],
  ja: [['実績データと来年の計画を含む年次報告 PPT を作成…','実績データの振り返りと来年の計画を含む年次報告 PPT の詳細な構成案を作成してください。'],['Excel の月次財務推移と異常値を分析…','この Excel の月次財務推移を分析し、異常値を特定して要約レポートを作成してください。'],['長文から要点、重要データ、結論を抽出…','この長文を要約し、主要な論点、重要データ、最終結論を抽出してください。'],['ビジネス文書を校正し正式な表現に改善…','この文書を校正し、誤りを直して正式なビジネス表現に整えてください。'],['構成を保った自然で専門的な対訳を作成…','次の文書を、構成を保ちながら自然で専門的な対訳に翻訳してください。'],['氏名、金額、日付などのデータを抽出…','次の文書から氏名、金額、日付などを抽出し、表形式で示してください。']],
  ko: [['성과와 내년 계획을 담은 연간 보고 PPT 작성…','성과 데이터와 내년 계획을 포함한 연간 보고 PPT 개요를 작성해 주세요.'],['Excel 월별 재무 추세와 이상 데이터 분석…','이 Excel의 월별 재무 추세를 분석하고 이상 데이터를 찾아 보고서를 작성해 주세요.'],['긴 문서의 핵심 내용과 결론 요약…','이 긴 문서를 요약하고 핵심 관점, 주요 데이터와 결론을 추출해 주세요.'],['비즈니스 문서를 교정하고 공식 문체로 개선…','이 문서를 전문적으로 교정하고 공식적인 비즈니스 문체로 다듬어 주세요.'],['구조를 유지한 자연스러운 이중 언어 번역…','다음 문서를 구조를 유지하면서 자연스럽고 전문적으로 번역해 주세요.'],['이름, 금액, 날짜 등의 데이터 추출…','문서에서 이름, 금액, 날짜 등의 데이터를 추출해 표로 보여 주세요.']],
  es: [['Crea un PPT anual con resultados y planes futuros…','Crea un esquema de PPT anual con resultados y planes para el próximo año.'],['Analiza tendencias financieras y anomalías…','Analiza las tendencias mensuales de este Excel y crea un informe.'],['Resume un documento largo y extrae conclusiones…','Resume este documento y extrae ideas, datos clave y conclusiones.'],['Mejora un documento comercial y corrige errores…','Mejora este documento con un tono comercial formal.'],['Crea una traducción bilingüe conservando la estructura…','Traduce el documento conservando su estructura y tono profesional.'],['Extrae nombres, importes, fechas y otros datos…','Extrae los datos estructurados y preséntalos en una tabla.']],
  pt: [['Crie um PPT anual com resultados e planos futuros…','Crie um roteiro de PPT anual com resultados e planos para o próximo ano.'],['Analise tendências financeiras e anomalias…','Analise as tendências mensais deste Excel e gere um relatório.'],['Resuma um documento longo e extraia conclusões…','Resuma o documento e extraia ideias, dados importantes e conclusões.'],['Aprimore um documento comercial e corrija erros…','Aprimore este documento com um tom comercial formal.'],['Crie uma tradução bilíngue preservando a estrutura…','Traduza o documento preservando a estrutura e o tom profissional.'],['Extraia nomes, valores, datas e outros dados…','Extraia os dados estruturados e apresente-os em uma tabela.']],
  fr: [['Créez un PPT annuel avec résultats et projets futurs…','Créez un plan de PPT annuel avec bilan et projets pour l’année prochaine.'],['Analysez les tendances financières et les anomalies…','Analysez les tendances mensuelles de cet Excel et créez un rapport.'],['Résumez un long document et extrayez ses conclusions…','Résumez ce document et extrayez les idées, données et conclusions.'],['Améliorez un document professionnel et corrigez les erreurs…','Améliorez ce document avec un ton commercial formel.'],['Créez une traduction bilingue en gardant la structure…','Traduisez le document en conservant sa structure et son ton professionnel.'],['Extrayez noms, montants, dates et autres données…','Extrayez les données structurées et présentez-les dans un tableau.']],
  de: [['Jahresbericht-PPT mit Ergebnissen und Ausblick erstellen…','Erstellen Sie eine PPT-Gliederung mit Rückblick und Planung für das nächste Jahr.'],['Finanztrends und Ausreißer analysieren…','Analysieren Sie die monatlichen Trends dieser Excel-Datei und erstellen Sie einen Bericht.'],['Langes Dokument zusammenfassen und Kernaussagen extrahieren…','Fassen Sie das Dokument zusammen und extrahieren Sie Kernaussagen, Daten und Ergebnisse.'],['Geschäftsdokument überarbeiten und Fehler korrigieren…','Überarbeiten Sie dieses Dokument in einem formellen Geschäftston.'],['Zweisprachige Übersetzung mit gleicher Struktur…','Übersetzen Sie das Dokument und bewahren Sie Struktur und professionellen Ton.'],['Namen, Beträge, Daten und weitere Angaben extrahieren…','Extrahieren Sie strukturierte Angaben und stellen Sie sie als Tabelle dar.']],
};
export function dashboardSuggestions(locale) { return suggestionValues[locale] || suggestionValues['zh-CN']; }
