const zh = {
  language: { select: '选择语言' },
  nav: { documents: '文档处理', features: '产品功能', solutions: '解决方案', pricing: '价格方案', login: '登录', start: '免费开始体验', home: 'OfficeGPT 首页', expand: '展开左侧导航', collapse: '收起左侧导航' },
  footer: { summary: '基于最新大语言模型驱动的下一代数据处理与办公自动化 SaaS 平台。', products: '产品与服务', workflow: '核心工作流', billing: '按量计费方案', docs: '帮助文档中心', legal: '法律与支持', about: '关于我们', privacy: '隐私政策', terms: '服务条款', rights: '© 2026 深圳市星尚硕教育科技有限公司 保留所有权利。' },
  faq: { title: '常见问题解答', subtitle: '了解更多关于 OfficeGPT 的核心优势与安全机制', items: [
    ['OfficeGPT 与传统 Excel/Word 相比有什么优势？', '无需记忆复杂函数或手动排版，只需使用自然语言描述目标，AI 即可完成计算、整理和排版。'],
    ['上传的文档数据安全吗？', '文档处理任务在隔离环境中运行，文件仅在处理期间使用，我们不会使用用户隐私数据训练模型。'],
    ['AI 是如何进行文档处理的？', 'AI 会理解自然语言意图，生成精准的操作步骤，并在安全环境中完成文档读取、计算、转换与生成。'],
    ['OfficeGPT 提供免费体验吗？', '是的，新用户可获得免费体验额度，用于体验智能排版、总结、翻译等核心能力。']
  ] },
};

const en = {
  language: { select: 'Select language' },
  nav: { documents: 'Document tools', features: 'Features', solutions: 'Solutions', pricing: 'Pricing', login: 'Log in', start: 'Start for free', home: 'OfficeGPT home', expand: 'Expand sidebar', collapse: 'Collapse sidebar' },
  footer: { summary: 'A next-generation SaaS platform for data processing and office automation, powered by large language models.', products: 'Products & services', workflow: 'Core workflow', billing: 'Usage-based pricing', docs: 'Help center', legal: 'Legal & support', about: 'About us', privacy: 'Privacy policy', terms: 'Terms of service', rights: '© 2026 Shenzhen Xingshangshuo Education Technology Co., Ltd. All rights reserved.' },
  faq: { title: 'Frequently asked questions', subtitle: 'Learn about OfficeGPT’s core benefits and security', items: [
    ['How is OfficeGPT better than traditional Excel or Word?', 'Describe your goal in natural language instead of memorizing formulas or formatting documents manually. AI handles calculations, organization, and layout.'],
    ['Is my uploaded document data secure?', 'Document tasks run in an isolated environment. Files are used only during processing, and private user data is never used to train models.'],
    ['How does AI process documents?', 'AI understands your intent, creates precise operation steps, and reads, calculates, converts, or generates documents in a secure environment.'],
    ['Does OfficeGPT offer a free trial?', 'Yes. New users receive free credits to try core features such as smart formatting, summarization, and translation.']
  ] },
};

const translations = {
  'zh-CN': zh,
  en,
  ja: {
    language: { select: '言語を選択' },
    nav: { documents: '文書処理', features: '機能', solutions: 'ソリューション', pricing: '料金', login: 'ログイン', start: '無料で始める', home: 'OfficeGPT ホーム', expand: 'サイドバーを開く', collapse: 'サイドバーを閉じる' },
    footer: { summary: '大規模言語モデルを活用した、次世代のデータ処理・オフィス自動化 SaaS プラットフォーム。', products: '製品とサービス', workflow: '主要ワークフロー', billing: '従量課金', docs: 'ヘルプセンター', legal: '法務・サポート', about: '会社概要', privacy: 'プライバシーポリシー', terms: '利用規約', rights: '© 2026 Shenzhen Xingshangshuo Education Technology Co., Ltd. All rights reserved.' },
    faq: { title: 'よくある質問', subtitle: 'OfficeGPT の主な特長とセキュリティについて', items: [['従来の Excel や Word との違いは？','数式や書式を覚えず、自然な言葉で目的を伝えるだけで AI が計算・整理・レイアウトを行います。'],['アップロードした文書は安全ですか？','処理は分離環境で実行され、ファイルは処理中のみ使用されます。個人データを学習には使用しません。'],['AI はどのように文書を処理しますか？','意図を理解して正確な操作手順を作成し、安全な環境で読み取り、計算、変換、生成を行います。'],['無料で試せますか？','はい。新規ユーザーには主要機能を試せる無料クレジットがあります。']] },
  },
  ko: {
    language: { select: '언어 선택' }, nav: { documents: '문서 처리', features: '제품 기능', solutions: '솔루션', pricing: '요금제', login: '로그인', start: '무료로 시작', home: 'OfficeGPT 홈', expand: '사이드바 열기', collapse: '사이드바 닫기' },
    footer: { summary: '대규모 언어 모델 기반의 차세대 데이터 처리 및 업무 자동화 SaaS 플랫폼입니다.', products: '제품 및 서비스', workflow: '핵심 워크플로', billing: '사용량 기반 요금', docs: '도움말 센터', legal: '법률 및 지원', about: '회사 소개', privacy: '개인정보 처리방침', terms: '서비스 약관', rights: '© 2026 Shenzhen Xingshangshuo Education Technology Co., Ltd. All rights reserved.' },
    faq: { title: '자주 묻는 질문', subtitle: 'OfficeGPT의 핵심 장점과 보안을 알아보세요', items: [['기존 Excel이나 Word와 무엇이 다른가요?','복잡한 수식이나 서식을 외울 필요 없이 자연어로 목표를 설명하면 AI가 계산, 정리, 서식을 처리합니다.'],['업로드한 문서는 안전한가요?','문서 작업은 격리된 환경에서 실행되며 파일은 처리 중에만 사용됩니다. 개인정보를 모델 학습에 사용하지 않습니다.'],['AI는 문서를 어떻게 처리하나요?','요청 의도를 이해하고 정확한 작업 단계를 만든 뒤 안전한 환경에서 읽기, 계산, 변환, 생성을 수행합니다.'],['무료 체험이 있나요?','네. 신규 사용자에게 핵심 기능을 체험할 수 있는 무료 크레딧을 제공합니다.']] },
  },
};

const western = {
  es: ['Seleccionar idioma','Herramientas de documentos','Funciones','Soluciones','Precios','Iniciar sesión','Comenzar gratis','Inicio de OfficeGPT','Expandir barra lateral','Contraer barra lateral','Plataforma SaaS de nueva generación para procesar datos y automatizar el trabajo con modelos de lenguaje.','Productos y servicios','Flujo principal','Precios por uso','Centro de ayuda','Legal y soporte','Sobre nosotros','Política de privacidad','Términos del servicio','Preguntas frecuentes','Conoce las ventajas y la seguridad de OfficeGPT'],
  pt: ['Selecionar idioma','Ferramentas de documentos','Recursos','Soluções','Preços','Entrar','Começar grátis','Início do OfficeGPT','Expandir barra lateral','Recolher barra lateral','Plataforma SaaS de nova geração para processamento de dados e automação de escritório com modelos de linguagem.','Produtos e serviços','Fluxo principal','Preços por uso','Central de ajuda','Jurídico e suporte','Sobre nós','Política de privacidade','Termos de serviço','Perguntas frequentes','Conheça as vantagens e a segurança do OfficeGPT'],
  fr: ['Choisir la langue','Outils de documents','Fonctionnalités','Solutions','Tarifs','Connexion','Commencer gratuitement','Accueil OfficeGPT','Déployer la barre latérale','Réduire la barre latérale','Plateforme SaaS nouvelle génération de traitement des données et d’automatisation bureautique propulsée par les grands modèles de langage.','Produits et services','Flux principal','Tarification à l’usage','Centre d’aide','Juridique et assistance','À propos','Politique de confidentialité','Conditions d’utilisation','Questions fréquentes','Découvrez les avantages et la sécurité d’OfficeGPT'],
  de: ['Sprache auswählen','Dokumentwerkzeuge','Funktionen','Lösungen','Preise','Anmelden','Kostenlos starten','OfficeGPT-Startseite','Seitenleiste öffnen','Seitenleiste schließen','SaaS-Plattform der nächsten Generation für Datenverarbeitung und Büroautomatisierung auf Basis großer Sprachmodelle.','Produkte und Dienste','Kernworkflow','Nutzungsbasierte Preise','Hilfe-Center','Rechtliches und Support','Über uns','Datenschutz','Nutzungsbedingungen','Häufig gestellte Fragen','Erfahren Sie mehr über die Vorteile und Sicherheit von OfficeGPT'],
};

for (const [locale, v] of Object.entries(western)) {
  translations[locale] = {
    language: { select: v[0] }, nav: { documents:v[1],features:v[2],solutions:v[3],pricing:v[4],login:v[5],start:v[6],home:v[7],expand:v[8],collapse:v[9] },
    footer: { summary:v[10],products:v[11],workflow:v[12],billing:v[13],docs:v[14],legal:v[15],about:v[16],privacy:v[17],terms:v[18],rights:en.footer.rights },
    faq: { title:v[19],subtitle:v[20],items:en.faq.items },
  };
}

const authText = {
  'zh-CN': ['欢迎回来，请登录您的账户','邮箱','密码','登录中…','登 录','还没有账号？','免费注册获赠 10,000 Credits','微信扫码登录','打开微信扫一扫，无需输入密码','扫码即表示同意','注册新账号，免费获赠 10,000 Credits','确认密码','设置一个安全的密码','再次输入密码','注册中…','免费注册','已有账号？','去登录','两次密码输入不一致','网络错误，请检查服务是否正常运行','登录失败，请稍后重试'],
  en: ['Welcome back. Sign in to your account','Email','Password','Signing in…','Log in','New to OfficeGPT?','Register free and get 10,000 Credits','Sign in with WeChat','Scan with WeChat — no password required','By scanning, you agree to the','Create an account and get 10,000 Credits free','Confirm password','Choose a secure password','Enter your password again','Creating account…','Register free','Already have an account?','Log in','Passwords do not match','Network error. Please check that the service is running.','Login failed. Please try again later.'],
  ja: ['おかえりなさい。アカウントにログインしてください','メールアドレス','パスワード','ログイン中…','ログイン','アカウントをお持ちでない方','無料登録で 10,000 Credits を獲得','WeChat でログイン','WeChat でスキャン。パスワードは不要です','スキャンすると、次の内容に同意したものとみなされます：','新規登録で 10,000 Credits を無料獲得','パスワード確認','安全なパスワードを設定','もう一度入力してください','登録中…','無料登録','すでにアカウントをお持ちですか？','ログイン','パスワードが一致しません','ネットワークエラーです。サービスの状態を確認してください。','ログインに失敗しました。後でもう一度お試しください。'],
  ko: ['다시 오신 것을 환영합니다. 계정에 로그인하세요','이메일','비밀번호','로그인 중…','로그인','계정이 없으신가요?','무료 가입하고 10,000 Credits 받기','WeChat으로 로그인','WeChat으로 스캔하면 비밀번호가 필요 없습니다','스캔하면 다음에 동의하게 됩니다:','가입하고 10,000 Credits를 무료로 받으세요','비밀번호 확인','안전한 비밀번호를 설정하세요','비밀번호를 다시 입력하세요','가입 중…','무료 가입','이미 계정이 있으신가요?','로그인','비밀번호가 일치하지 않습니다','네트워크 오류입니다. 서비스 상태를 확인하세요.','로그인하지 못했습니다. 잠시 후 다시 시도하세요.'],
  es: ['Te damos la bienvenida. Inicia sesión','Correo electrónico','Contraseña','Iniciando sesión…','Iniciar sesión','¿Aún no tienes cuenta?','Regístrate gratis y recibe 10.000 Credits','Iniciar sesión con WeChat','Escanea con WeChat, sin contraseña','Al escanear, aceptas los','Crea una cuenta y recibe 10.000 Credits gratis','Confirmar contraseña','Elige una contraseña segura','Vuelve a escribir la contraseña','Creando cuenta…','Registro gratuito','¿Ya tienes una cuenta?','Iniciar sesión','Las contraseñas no coinciden','Error de red. Comprueba que el servicio esté activo.','No se pudo iniciar sesión. Inténtalo más tarde.'],
  pt: ['Bem-vindo de volta. Entre na sua conta','E-mail','Senha','Entrando…','Entrar','Ainda não tem uma conta?','Cadastre-se grátis e ganhe 10.000 Credits','Entrar com WeChat','Leia com o WeChat, sem precisar de senha','Ao ler o código, você concorda com os','Crie uma conta e ganhe 10.000 Credits grátis','Confirmar senha','Escolha uma senha segura','Digite a senha novamente','Criando conta…','Cadastro grátis','Já tem uma conta?','Entrar','As senhas não coincidem','Erro de rede. Verifique se o serviço está ativo.','Falha ao entrar. Tente novamente mais tarde.'],
  fr: ['Ravi de vous revoir. Connectez-vous à votre compte','E-mail','Mot de passe','Connexion…','Se connecter','Vous n’avez pas de compte ?','Inscrivez-vous et recevez 10 000 Credits','Connexion avec WeChat','Scannez avec WeChat, sans mot de passe','En scannant, vous acceptez les','Créez un compte et recevez 10 000 Credits','Confirmer le mot de passe','Choisissez un mot de passe sécurisé','Saisissez à nouveau le mot de passe','Création du compte…','Inscription gratuite','Vous avez déjà un compte ?','Se connecter','Les mots de passe ne correspondent pas','Erreur réseau. Vérifiez que le service fonctionne.','Échec de la connexion. Réessayez plus tard.'],
  de: ['Willkommen zurück. Melden Sie sich an','E-Mail','Passwort','Anmeldung läuft…','Anmelden','Noch kein Konto?','Kostenlos registrieren und 10.000 Credits erhalten','Mit WeChat anmelden','Mit WeChat scannen – kein Passwort nötig','Durch das Scannen akzeptieren Sie die','Konto erstellen und 10.000 Credits erhalten','Passwort bestätigen','Wählen Sie ein sicheres Passwort','Passwort erneut eingeben','Konto wird erstellt…','Kostenlos registrieren','Sie haben bereits ein Konto?','Anmelden','Die Passwörter stimmen nicht überein','Netzwerkfehler. Prüfen Sie, ob der Dienst läuft.','Anmeldung fehlgeschlagen. Versuchen Sie es später erneut.'],
};

for (const [locale, v] of Object.entries(authText)) {
  translations[locale].auth = { welcome:v[0],email:v[1],password:v[2],signingIn:v[3],login:v[4],noAccount:v[5],registerBonus:v[6],wechat:v[7],wechatHint:v[8],scanAgreement:v[9],registerIntro:v[10],confirmPassword:v[11],passwordPlaceholder:v[12],confirmPlaceholder:v[13],registering:v[14],register:v[15],hasAccount:v[16],goLogin:v[17],passwordMismatch:v[18],networkError:v[19],loginFailed:v[20] };
}

const dashboardText = {
  'zh-CN':['开启新任务','数据概览','账单与流水','历史记录','当前可用 Credits','微信支付充值','账单明细','时间','类型','任务与模型','Token 用量','结算金额','余额','上一页','下一页','共 {count} 条','账户余额变动'],
  en:['New chat','Overview','Billing & transactions','Recent','Available Credits','Top up with WeChat Pay','Transaction details','Time','Type','Task & model','Token usage','Amount','Balance','Previous','Next','{count} records','Account balance change'],
  ja:['新しいチャット','概要','請求と取引','履歴','利用可能な Credits','WeChat Pay でチャージ','取引明細','日時','種類','タスクとモデル','Token 使用量','決済額','残高','前へ','次へ','全 {count} 件','残高の変更'],
  ko:['새 채팅','개요','청구 및 거래','최근 기록','사용 가능 Credits','WeChat Pay 충전','거래 내역','시간','유형','작업 및 모델','Token 사용량','결제 금액','잔액','이전','다음','총 {count}건','계정 잔액 변경'],
  es:['Nuevo chat','Resumen','Facturación y movimientos','Recientes','Credits disponibles','Recargar con WeChat Pay','Detalle de movimientos','Fecha y hora','Tipo','Tarea y modelo','Uso de Token','Importe','Saldo','Anterior','Siguiente','{count} registros','Cambio de saldo'],
  pt:['Novo chat','Visão geral','Faturamento e transações','Recentes','Credits disponíveis','Recarregar com WeChat Pay','Detalhes das transações','Data e hora','Tipo','Tarefa e modelo','Uso de Token','Valor','Saldo','Anterior','Próxima','{count} registros','Alteração de saldo'],
  fr:['Nouveau chat','Vue d’ensemble','Facturation et opérations','Récents','Credits disponibles','Recharger avec WeChat Pay','Détail des opérations','Date et heure','Type','Tâche et modèle','Utilisation des Token','Montant','Solde','Précédent','Suivant','{count} opérations','Variation du solde'],
  de:['Neuer Chat','Übersicht','Abrechnung und Transaktionen','Zuletzt','Verfügbare Credits','Mit WeChat Pay aufladen','Transaktionsdetails','Datum und Uhrzeit','Typ','Aufgabe und Modell','Token-Nutzung','Betrag','Guthaben','Zurück','Weiter','{count} Einträge','Guthabenänderung'],
};
for (const [locale, v] of Object.entries(dashboardText)) translations[locale].dashboard = { newChat:v[0],overview:v[1],billing:v[2],recent:v[3],available:v[4],wechatTopup:v[5],details:v[6],time:v[7],type:v[8],taskModel:v[9],tokens:v[10],amount:v[11],balance:v[12],previous:v[13],next:v[14],count:v[15],balanceChange:v[16] };

const toolsText = {
  'zh-CN':['全能文档处理大厅','{count} 个真正可用的 PDF、Office、数据转换和 AI 文档工具。免费完成基础处理，需要更进一步时交给 Office AI。','搜索 PDF、Word、Excel、PPT 或 AI 工具','搜索工具','没有找到匹配工具。你也可以进入 Office AI，直接描述想完成的任务。','询问 Office AI','使用 Office AI 开始处理','上传文件并开始','文件正在安全处理中…','处理失败，请重试','处理成功！','点击或拖拽上传文件','支持 {formats} 格式，全程加密处理','已准备好 {count} 个文件','处理中…','立即开始处理','您的文件 {filename} 已经准备就绪。','下载处理结果','处理另一份文件','关于 {name}','适合这些场景','常见问题','相关工具','处理完成后，让 Office AI 继续工作','总结、翻译、分析数据，或直接生成 Word、Excel 和 PPT。','进入 Office AI','该工具可快速、安全地完成 {name}，完成后还可以交给 Office AI 继续处理。','快速完成日常文档任务','批量整理和交付办公文件','继续使用 AI 分析处理结果','文件安全吗？','文件仅用于当前处理任务，不会发送到第三方转换网站。','处理后还能继续编辑吗？','可以下载结果，也可以进入 Office AI 继续处理。'],
  en:['Document Tool Center','{count} production-ready PDF, Office, data conversion, and AI document tools. Use core processing for free, then continue with Office AI when needed.','Search PDF, Word, Excel, PPT, or AI tools','Search tools','No matching tools found. You can also describe your task directly to Office AI.','Ask Office AI','Start with Office AI','Upload and start','Processing your file securely…','Processing failed. Please try again.','Processing complete!','Click or drag files here','Supports {formats}; encrypted throughout processing','{count} files ready','Processing…','Start processing','Your file {filename} is ready.','Download result','Process another file','About {name}','Best for','Frequently asked questions','Related tools','Continue with Office AI','Summarize, translate, analyze data, or generate Word, Excel, and PPT files.','Open Office AI','Use {name} quickly and securely, then continue editing or analyzing the result with Office AI.','Complete routine document tasks quickly','Organize and deliver office files in batches','Continue analyzing the result with AI','Are my files secure?','Files are used only for this task and are not sent to third-party conversion sites.','Can I continue editing afterward?','Yes. Download the result or continue working in Office AI.'],
  ja:['文書ツールセンター','すぐに使える PDF、Office、データ変換、AI 文書ツールが {count} 個。基本処理は無料で、必要に応じて Office AI で続行できます。','PDF、Word、Excel、PPT、AI ツールを検索','ツールを検索','一致するツールがありません。Office AI に直接作業内容を伝えることもできます。','Office AI に質問','Office AI で開始','アップロードして開始','ファイルを安全に処理しています…','処理に失敗しました。もう一度お試しください。','処理が完了しました！','クリックまたはドラッグしてアップロード','対応形式：{formats}。処理中は暗号化されます','{count} 個のファイルを準備しました','処理中…','処理を開始','ファイル {filename} の準備ができました。','結果をダウンロード','別のファイルを処理','{name} について','利用シーン','よくある質問','関連ツール','Office AI で作業を続ける','要約、翻訳、データ分析、Word・Excel・PPT の生成ができます。','Office AI を開く','{name} をすばやく安全に実行し、結果を Office AI で続けて編集・分析できます。','日常の文書作業をすばやく完了','オフィスファイルをまとめて整理・納品','AI で結果をさらに分析','ファイルは安全ですか？','ファイルは現在の処理にのみ使用され、外部の変換サイトには送信されません。','処理後も編集できますか？','結果をダウンロードするか、Office AI で続けて編集できます。'],
  ko:['문서 도구 센터','바로 사용할 수 있는 PDF, Office, 데이터 변환 및 AI 문서 도구 {count}개. 기본 처리는 무료이며 필요하면 Office AI에서 계속할 수 있습니다.','PDF, Word, Excel, PPT 또는 AI 도구 검색','도구 검색','일치하는 도구가 없습니다. Office AI에 원하는 작업을 직접 설명할 수도 있습니다.','Office AI에 질문','Office AI로 시작','업로드하고 시작','파일을 안전하게 처리하는 중…','처리하지 못했습니다. 다시 시도하세요.','처리가 완료되었습니다!','클릭하거나 파일을 끌어 업로드','{formats} 형식 지원, 처리 과정 암호화','파일 {count}개 준비됨','처리 중…','처리 시작','파일 {filename}이 준비되었습니다.','결과 다운로드','다른 파일 처리','{name} 소개','추천 활용 사례','자주 묻는 질문','관련 도구','Office AI에서 계속 작업','요약, 번역, 데이터 분석 또는 Word, Excel, PPT 파일을 생성하세요.','Office AI 열기','{name} 작업을 빠르고 안전하게 수행한 뒤 Office AI에서 계속 편집하거나 분석할 수 있습니다.','일상 문서 작업을 빠르게 완료','오피스 파일 일괄 정리 및 전달','AI로 결과 계속 분석','파일은 안전한가요?','파일은 현재 작업에만 사용되며 외부 변환 사이트로 전송되지 않습니다.','처리 후에도 편집할 수 있나요?','결과를 다운로드하거나 Office AI에서 계속 작업할 수 있습니다.'],
  es:['Centro de herramientas de documentos','{count} herramientas listas para PDF, Office, conversión de datos y documentos con IA. Usa el procesamiento básico gratis y continúa con Office AI.','Buscar herramientas PDF, Word, Excel, PPT o IA','Buscar herramientas','No hay herramientas coincidentes. También puedes describir la tarea directamente a Office AI.','Preguntar a Office AI','Empezar con Office AI','Subir y empezar','Procesando el archivo de forma segura…','No se pudo procesar. Inténtalo de nuevo.','¡Proceso completado!','Haz clic o arrastra archivos aquí','Admite {formats}; procesamiento cifrado','{count} archivos preparados','Procesando…','Empezar a procesar','El archivo {filename} está listo.','Descargar resultado','Procesar otro archivo','Acerca de {name}','Casos recomendados','Preguntas frecuentes','Herramientas relacionadas','Continúa con Office AI','Resume, traduce, analiza datos o genera archivos Word, Excel y PPT.','Abrir Office AI','Usa {name} de forma rápida y segura, y continúa editando o analizando con Office AI.','Completar tareas documentales habituales','Organizar y entregar archivos por lotes','Seguir analizando el resultado con IA','¿Mis archivos están seguros?','Los archivos solo se usan para esta tarea y no se envían a sitios de conversión externos.','¿Puedo seguir editando después?','Sí. Descarga el resultado o continúa en Office AI.'],
  pt:['Central de ferramentas de documentos','{count} ferramentas prontas para PDF, Office, conversão de dados e documentos com IA. Use o processamento básico grátis e continue no Office AI.','Pesquisar ferramentas PDF, Word, Excel, PPT ou IA','Pesquisar ferramentas','Nenhuma ferramenta encontrada. Você também pode descrever a tarefa diretamente ao Office AI.','Perguntar ao Office AI','Começar com Office AI','Enviar e começar','Processando o arquivo com segurança…','Falha no processamento. Tente novamente.','Processamento concluído!','Clique ou arraste arquivos aqui','Compatível com {formats}; processamento criptografado','{count} arquivos prontos','Processando…','Iniciar processamento','O arquivo {filename} está pronto.','Baixar resultado','Processar outro arquivo','Sobre {name}','Melhores casos de uso','Perguntas frequentes','Ferramentas relacionadas','Continue no Office AI','Resuma, traduza, analise dados ou gere arquivos Word, Excel e PPT.','Abrir Office AI','Use {name} com rapidez e segurança e continue editando ou analisando no Office AI.','Concluir tarefas comuns de documentos','Organizar e entregar arquivos em lote','Continuar a análise com IA','Meus arquivos estão seguros?','Os arquivos são usados apenas nesta tarefa e não são enviados a sites de conversão externos.','Posso continuar editando depois?','Sim. Baixe o resultado ou continue no Office AI.'],
  fr:['Centre d’outils documentaires','{count} outils prêts à l’emploi pour PDF, Office, la conversion de données et les documents IA. Traitement de base gratuit, puis continuez avec Office AI.','Rechercher des outils PDF, Word, Excel, PPT ou IA','Rechercher des outils','Aucun outil correspondant. Vous pouvez aussi décrire directement votre tâche à Office AI.','Demander à Office AI','Commencer avec Office AI','Importer et commencer','Traitement sécurisé du fichier…','Échec du traitement. Réessayez.','Traitement terminé !','Cliquez ou déposez des fichiers ici','Formats {formats} pris en charge ; traitement chiffré','{count} fichiers prêts','Traitement…','Lancer le traitement','Votre fichier {filename} est prêt.','Télécharger le résultat','Traiter un autre fichier','À propos de {name}','Cas d’usage','Questions fréquentes','Outils associés','Continuez avec Office AI','Résumez, traduisez, analysez des données ou générez des fichiers Word, Excel et PPT.','Ouvrir Office AI','Utilisez {name} rapidement et en toute sécurité, puis poursuivez l’édition ou l’analyse avec Office AI.','Effectuer rapidement les tâches documentaires','Organiser et livrer des fichiers par lot','Poursuivre l’analyse avec l’IA','Mes fichiers sont-ils sécurisés ?','Les fichiers servent uniquement à cette tâche et ne sont pas envoyés à des sites de conversion tiers.','Puis-je continuer à modifier le résultat ?','Oui. Téléchargez-le ou continuez dans Office AI.'],
  de:['Dokument-Toolcenter','{count} einsatzbereite Tools für PDF, Office, Datenkonvertierung und KI-Dokumente. Basisverarbeitung kostenlos, anschließend mit Office AI weiterarbeiten.','PDF-, Word-, Excel-, PPT- oder KI-Tools suchen','Tools suchen','Keine passenden Tools gefunden. Sie können die Aufgabe auch direkt Office AI beschreiben.','Office AI fragen','Mit Office AI starten','Hochladen und starten','Datei wird sicher verarbeitet…','Verarbeitung fehlgeschlagen. Bitte erneut versuchen.','Verarbeitung abgeschlossen!','Klicken oder Dateien hierher ziehen','Unterstützt {formats}; verschlüsselte Verarbeitung','{count} Dateien bereit','Verarbeitung…','Verarbeitung starten','Die Datei {filename} ist bereit.','Ergebnis herunterladen','Weitere Datei verarbeiten','Über {name}','Geeignet für','Häufige Fragen','Ähnliche Tools','Mit Office AI weiterarbeiten','Zusammenfassen, übersetzen, Daten analysieren oder Word-, Excel- und PPT-Dateien erstellen.','Office AI öffnen','{name} schnell und sicher nutzen und das Ergebnis anschließend mit Office AI bearbeiten oder analysieren.','Tägliche Dokumentaufgaben schnell erledigen','Office-Dateien gesammelt organisieren und liefern','Ergebnis mit KI weiter analysieren','Sind meine Dateien sicher?','Dateien werden nur für diesen Auftrag verwendet und nicht an externe Konvertierungsseiten gesendet.','Kann ich danach weiterarbeiten?','Ja. Laden Sie das Ergebnis herunter oder arbeiten Sie in Office AI weiter.'],
};
for (const [locale, v] of Object.entries(toolsText)) translations[locale].tools = { title:v[0],subtitle:v[1],search:v[2],searchLabel:v[3],empty:v[4],askAi:v[5],aiStart:v[6],uploadStart:v[7],processingToast:v[8],failed:v[9],success:v[10],drop:v[11],formats:v[12],filesReady:v[13],processing:v[14],start:v[15],fileReady:v[16],download:v[17],another:v[18],about:v[19],useCases:v[20],faq:v[21],related:v[22],continueTitle:v[23],continueText:v[24],openAi:v[25],genericSummary:v[26],caseQuick:v[27],caseBatch:v[28],caseAi:v[29],safeQ:v[30],safeA:v[31],editQ:v[32],editA:v[33] };

const toolShellText = {
  'zh-CN':['文档工具导航','文档工具','免费在线处理','返回全部工具','复杂任务交给 AI',['格式极速转换','表格与数据转换','PDF 实用工具箱','AI 智能文档处理']],
  en:['Document tools navigation','Document tools','Free online processing','Back to all tools','Let AI handle complex tasks',['Fast format conversion','Spreadsheet & data conversion','PDF utilities','AI document processing']],
  ja:['文書ツールナビゲーション','文書ツール','無料オンライン処理','すべてのツールに戻る','複雑な作業は AI にお任せ',['高速形式変換','表計算・データ変換','PDF ユーティリティ','AI 文書処理']],
  ko:['문서 도구 탐색','문서 도구','무료 온라인 처리','모든 도구로 돌아가기','복잡한 작업은 AI에게',['빠른 형식 변환','스프레드시트 및 데이터 변환','PDF 유틸리티','AI 문서 처리']],
  es:['Navegación de herramientas','Herramientas','Proceso gratuito en línea','Volver a todas las herramientas','Deja las tareas complejas a la IA',['Conversión rápida','Hojas y datos','Utilidades PDF','Documentos con IA']],
  pt:['Navegação de ferramentas','Ferramentas','Processamento online grátis','Voltar a todas as ferramentas','Deixe tarefas complexas para a IA',['Conversão rápida','Planilhas e dados','Utilitários PDF','Documentos com IA']],
  fr:['Navigation des outils','Outils documentaires','Traitement gratuit en ligne','Retour à tous les outils','Confiez les tâches complexes à l’IA',['Conversion rapide','Feuilles et données','Utilitaires PDF','Documents par IA']],
  de:['Navigation der Dokumenttools','Dokumenttools','Kostenlos online verarbeiten','Zurück zu allen Tools','Komplexe Aufgaben der KI überlassen',['Schnelle Konvertierung','Tabellen und Daten','PDF-Werkzeuge','KI-Dokumente']],
};
for (const [locale, v] of Object.entries(toolShellText)) Object.assign(translations[locale].tools, { nav:v[0],shellTitle:v[1],freeOnline:v[2],backAll:v[3],aiComplex:v[4],categories:v[5] });

export default translations;
